sudo: false
language: node_js
scripts:
  - npm install codecov -g
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - 8
  - 10
after_success:
  - npm run build
  - codecov
branches:
  only:
    - master
	- develop
